{% set name = "mockmpi" %}
{% set version = "0.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/rmjarvis/MockMPI/archive/refs/tags/v{{ version }}.tar.gz
  sha256: a7161711520f8dca288e3aa2aa8c8a5dbff0c3020feefb7df464d72598634529

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - numpy

test:
  imports:
    - mockmpi

about:
  home: https://github.com/rmjarvis/MockMPI
  summary: 'A tool for mocking mpi4py for testing'
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - beckermr
