{% set name = "mockmpi" %}
{% set version = "0.8.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/rmjarvis/MockMPI/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 6049885728adf65e4121d4a47b10b28c37de4f87bab5a475a1ac97a9ff8a525e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - numpy

test:
  requires:
    - python {{ python_min }}
  imports:
    - mockmpi

about:
  home: https://github.com/rmjarvis/MockMPI
  summary: 'A tool for mocking mpi4py for testing'
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - beckermr
